
$(document).ready(function(){
    $('.faqkep01').click(function(){
      $('.faq01').slideToggle("slow");
      $('.faqkep01').toggleClass('faqkep01m');
    });
    $('.faqkep02').click(function(){
      $('.faq02').slideToggle("slow");
      $('.faqkep02').toggleClass('faqkep02m');
    });$('.faqkep03').click(function(){
      $('.faq03').slideToggle("slow");
      $('.faqkep03').toggleClass('faqkep03m');
    });$('.faqkep04').click(function(){
      $('.faq04').slideToggle("slow");
      $('.faqkep04').toggleClass('faqkep04m');
    });$('.faqkep05').click(function(){
      $('.faq05').slideToggle("slow");
      $('.faqkep05').toggleClass('faqkep05m');
    });$('.faqkep06').click(function(){
      $('.faq06').slideToggle("slow");
      $('.faqkep06').toggleClass('faqkep06m');
    });$('.faqkep07').click(function(){
      $('.faq07').slideToggle("slow");
      $('.faqkep07').toggleClass('faqkep07m');
    });$('.faqkep08').click(function(){
      $('.faq08').slideToggle("slow");
      $('.faqkep08').toggleClass('faqkep08m');
    });$('.faqkep09').click(function(){
      $('.faq09').slideToggle("slow");
      $('.faqkep09').toggleClass('faqkep09m');
    });$('.faqkep10').click(function(){
      $('.faq10').slideToggle("slow");
      $('.faqkep10').toggleClass('faqkep10m');
    });$('.faqkep11').click(function(){
      $('.faq11').slideToggle("slow");
      $('.faqkep11').toggleClass('faqkep11m');
    });$('.faqkep12').click(function(){
      $('.faq12').slideToggle("slow");
      $('.faqkep12').toggleClass('faqkep12m');
    });
});
